import requests
import sys
from pathlib import Path


USERNAME = "jiefia"
README_PATH = "README.md"
SYNC_FOLDER = "action-sync"


def generate_bar(count, max_count, total_bar_length=25):
    if max_count == 0:
        return ""
    filled_length = int(total_bar_length * count // max_count)
    return "█" * filled_length


def get_proficiency(count):
    if count >= 50:
        return "⭐⭐⭐⭐⭐"
    elif count >= 30:
        return "⭐⭐⭐⭐"
    elif count >= 15:
        return "⭐⭐⭐"
    elif count >= 5:
        return "⭐⭐"
    else:
        return "⭐"


def count_synced_problems(folder_name=SYNC_FOLDER):
    """
    Count folders generated by GitHub Action sync.
    Example folder name: action-sync/0001-two-sum
    """
    folder = Path(folder_name)

    if not folder.exists():
        return 0

    count = 0
    for item in folder.iterdir():
        if item.is_dir() and item.name[:4].isdigit():
            count += 1

    return count


def fetch_leetcode_data(username):
    url = "https://leetcode.com/graphql"
    headers = {
        "User-Agent": "Mozilla/5.0",
        "Content-Type": "application/json",
        "Referer": f"https://leetcode.com/{username}/",
        "Origin": "https://leetcode.com",
        "Cache-Control": "no-cache",
        "Pragma": "no-cache",
    }

    query = """
    query userProfile($username: String!) {
      matchedUser(username: $username) {
        username
        submitStatsGlobal {
          acSubmissionNum {
            difficulty
            count
          }
        }
        languageProblemCount {
          languageName
          problemsSolved
        }
        tagProblemCounts {
          advanced {
            tagName
            problemsSolved
          }
          intermediate {
            tagName
            problemsSolved
          }
          fundamental {
            tagName
            problemsSolved
          }
        }
      }
    }
    """

    payload = {
        "query": query,
        "variables": {
            "username": username
        }
    }

    try:
        response = requests.post(url, json=payload, headers=headers, timeout=15)
        response.raise_for_status()
        data = response.json()

        if data.get("errors"):
            print("❌ LeetCode API returned errors:")
            print(data["errors"])
            return None

        return data.get("data", {}).get("matchedUser")

    except Exception as e:
        print(f"❌ Failed to fetch LeetCode data: {e}")
        return None


def build_markdown(user_info, synced_count):
    md_content = ""

    submit_stats = user_info.get("submitStatsGlobal", {}).get("acSubmissionNum", [])

    diff_counts = {
        "Easy": 0,
        "Medium": 0,
        "Hard": 0,
        "All": 0
    }

    for stat in submit_stats:
        diff_counts[stat["difficulty"]] = stat["count"]

    total = diff_counts["All"]
    easy_c = diff_counts["Easy"]
    med_c = diff_counts["Medium"]
    hard_c = diff_counts["Hard"]

    md_content += "\n### 📈 题目难度分布 | Live Stats\n\n"
    md_content += f"**LeetCode 官方解决数**: {total} 题\n\n"
    md_content += f"**GitHub Repo 已同步题目数**: {synced_count} 题\n\n"

    if total > 0:
        md_content += "```text\n"
        md_content += f"Easy   {generate_bar(easy_c, total, 25):<25} {easy_c:>3} 题 ({easy_c / total * 100:.1f}%)\n"
        md_content += f"Medium {generate_bar(med_c, total, 25):<25} {med_c:>3} 题 ({med_c / total * 100:.1f}%)\n"
        md_content += f"Hard   {generate_bar(hard_c, total, 25):<25} {hard_c:>3} 题 ({hard_c / total * 100:.1f}%)\n"
        md_content += "```\n"

    md_content += "\n### 📊 编程语言分布\n\n"
    md_content += "| 语言 | 题数 | 熟练度 |\n"
    md_content += "| :--- | :---: | :--- |\n"

    langs = user_info.get("languageProblemCount", [])
    if langs:
        langs.sort(key=lambda x: x["problemsSolved"], reverse=True)
        for lang in langs:
            language_name = lang["languageName"]
            solved = lang["problemsSolved"]
            md_content += f"| **{language_name}** | {solved} | {get_proficiency(solved)} |\n"
    else:
        md_content += "| 暂无 | 0 | - |\n"

    md_content += "\n### 🧩 刷题类型统计\n\n"
    md_content += "| 类型 | 题目数 | 进度图 |\n"
    md_content += "| :--- | :---: | :--- |\n"

    tags_data = user_info.get("tagProblemCounts", {})
    all_tags = []

    for level in ["advanced", "intermediate", "fundamental"]:
        if tags_data.get(level):
            all_tags.extend(tags_data[level])

    if all_tags:
        all_tags.sort(key=lambda x: x["problemsSolved"], reverse=True)
        max_problems = all_tags[0]["problemsSolved"]

        for skill in all_tags[:15]:
            tag_name = skill["tagName"]
            count = skill["problemsSolved"]
            bar = generate_bar(count, max_problems, total_bar_length=20)
            md_content += f"| **{tag_name}** | {count} | {bar} |\n"
    else:
        md_content += "| 暂无数据 | 0 | - |\n"

    return md_content


def update_readme(md_content):
    with open(README_PATH, "r", encoding="utf-8") as f:
        content = f.read()

    start_marker = "<!-- START -->"
    end_marker = "<!-- END -->"

    start_idx = content.find(start_marker)
    end_idx = content.rfind(end_marker)

    if start_idx == -1 or end_idx == -1 or end_idx <= start_idx:
        print("❌ README markers missing.")
        print("Please add <!-- START --> and <!-- END --> to README.md.")
        sys.exit(1)

    before_content = content[:start_idx + len(start_marker)]
    after_content = content[end_idx:]

    new_content = before_content + "\n" + md_content + "\n" + after_content

    with open(README_PATH, "w", encoding="utf-8") as f:
        f.write(new_content)

    print("🎉 README updated successfully!")


def main():
    synced_count = count_synced_problems(SYNC_FOLDER)
    user_info = fetch_leetcode_data(USERNAME)

    if not user_info:
        print("❌ Data sync failed. Script exited.")
        sys.exit(1)

    md_content = build_markdown(user_info, synced_count)
    update_readme(md_content)


if __name__ == "__main__":
    main()
